# Generated by Django 4.1.6 on 2023-02-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='publicado')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='noticias/media')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='noticias/media')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='noticias/media')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='noticias/media')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='noticias/media')),
                ('votos', models.IntegerField(default=0)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_noticias.temas')),
            ],
        ),
    ]
